// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"time"
)

type Activity struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	DateStart time.Time `json:"date_start"`
	DateEnd   time.Time `json:"date_end"`
	ProjectID int32     `json:"project_id"`
	UserID    int32     `json:"user_id"`
}

type Project struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Rate int32  `json:"rate"`
}
