// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package repository

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, name, rate
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Rate)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, rate = $2
WHERE id = $3
RETURNING id, name, rate
`

type UpdateUserParams struct {
	Name string `json:"name"`
	Rate int32  `json:"rate"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Name, arg.Rate, arg.ID)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.Rate)
	return i, err
}
